/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vendingMachine;


import javax.swing.JTextField;
import static vendingMachine.Methods.*;
/**
 *
 * @author cagla
 */
public class Float extends javax.swing.JFrame {
    
   public static int twoEuro = 0;
   public static int oneEuro = 0;
   public static int fiftyCent =0;
   public static int twentyCent =0;
   
   public void SetToZero() {
   twoEuroTF.setText("0");
   oneEuroTF.setText("0");
   fiftyCentTF.setText("0");
   twentyCentTF.setText("0");
   }
   
   public void GetFloat() {
   twoEuroTF.getText();
   oneEuroTF.getText();
   fiftyCentTF.getText();
   twentyCentTF.getText();
   }
   
   public void SetText(JTextField name, int value) {
        name.setText(value + "");
    }
   

    /**
     * Creates new form Float
     */
    public Float() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        twoEuroLabel = new javax.swing.JLabel();
        oneEuroLabel = new javax.swing.JLabel();
        fiftyCentLabel = new javax.swing.JLabel();
        twentyCentLabel = new javax.swing.JLabel();
        twoEuroTF = new javax.swing.JTextField();
        oneEuroTF = new javax.swing.JTextField();
        fiftyCentTF = new javax.swing.JTextField();
        twentyCentTF = new javax.swing.JTextField();
        okBTN = new javax.swing.JButton();
        cancelBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();
        twoEuroIncrementBTN = new javax.swing.JButton();
        onEuroeIncrementBTN = new javax.swing.JButton();
        fiftyCentIncrementBTN = new javax.swing.JButton();
        twentyCentIncrementBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Float Balancing");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        twoEuroLabel.setText("2 €");

        oneEuroLabel.setText("1 €");

        fiftyCentLabel.setText("50c");

        twentyCentLabel.setText("20c");

        twoEuroTF.setEditable(false);
        twoEuroTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        twoEuroTF.setToolTipText("Added amount");
        twoEuroTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoEuroTFActionPerformed(evt);
            }
        });

        oneEuroTF.setEditable(false);
        oneEuroTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        oneEuroTF.setToolTipText("Added amount");

        fiftyCentTF.setEditable(false);
        fiftyCentTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fiftyCentTF.setToolTipText("Added amount");

        twentyCentTF.setEditable(false);
        twentyCentTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        twentyCentTF.setToolTipText("Added amount");

        okBTN.setMnemonic('o');
        okBTN.setText("OK");
        okBTN.setToolTipText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        cancelBTN.setMnemonic('a');
        cancelBTN.setText("Cancel");
        cancelBTN.setToolTipText("Cancel");
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });

        clearBTN.setMnemonic('c');
        clearBTN.setText("Clear");
        clearBTN.setToolTipText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        twoEuroIncrementBTN.setText("+");
        twoEuroIncrementBTN.setToolTipText("Add");
        twoEuroIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoEuroIncrementBTNActionPerformed(evt);
            }
        });

        onEuroeIncrementBTN.setText("+");
        onEuroeIncrementBTN.setToolTipText("Add");
        onEuroeIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEuroeIncrementBTNActionPerformed(evt);
            }
        });

        fiftyCentIncrementBTN.setText("+");
        fiftyCentIncrementBTN.setToolTipText("Add");
        fiftyCentIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiftyCentIncrementBTNActionPerformed(evt);
            }
        });

        twentyCentIncrementBTN.setText("+");
        twentyCentIncrementBTN.setToolTipText("Add");
        twentyCentIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyCentIncrementBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(twentyCentLabel)
                            .addComponent(fiftyCentLabel)
                            .addComponent(oneEuroLabel)
                            .addComponent(twoEuroLabel))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(twoEuroTF, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(oneEuroTF)
                            .addComponent(fiftyCentTF)
                            .addComponent(twentyCentTF)))
                    .addComponent(okBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(twoEuroIncrementBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(onEuroeIncrementBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fiftyCentIncrementBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(twentyCentIncrementBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelBTN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(twoEuroIncrementBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twoEuroTF)
                    .addComponent(twoEuroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(onEuroeIncrementBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oneEuroTF)
                    .addComponent(oneEuroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fiftyCentIncrementBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fiftyCentTF)
                    .addComponent(fiftyCentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(twentyCentIncrementBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twentyCentTF)
                    .addComponent(twentyCentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBTN)
                    .addComponent(cancelBTN))
                .addGap(18, 18, 18)
                .addComponent(clearBTN)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void twoEuroIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoEuroIncrementBTNActionPerformed
        twoEuro++;
        SetText(twoEuroTF,twoEuro);
    }//GEN-LAST:event_twoEuroIncrementBTNActionPerformed

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        CleanFloat();
        SetToZero();
        dispose();
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        CleanFloat();
        SetToZero();
    }//GEN-LAST:event_formWindowOpened

    private void twoEuroTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoEuroTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoEuroTFActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        CleanFloat();
        SetToZero();
    }//GEN-LAST:event_clearBTNActionPerformed

    private void onEuroeIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEuroeIncrementBTNActionPerformed
       oneEuro++;
       SetText(oneEuroTF,oneEuro);
    }//GEN-LAST:event_onEuroeIncrementBTNActionPerformed

    private void fiftyCentIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiftyCentIncrementBTNActionPerformed
        fiftyCent++;
        SetText(fiftyCentTF,fiftyCent);           
    }//GEN-LAST:event_fiftyCentIncrementBTNActionPerformed

    private void twentyCentIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyCentIncrementBTNActionPerformed
        twentyCent++;
        SetText(twentyCentTF,twentyCent);
    }//GEN-LAST:event_twentyCentIncrementBTNActionPerformed

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        GetFloat();
        dispose();
    }//GEN-LAST:event_okBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Float.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Float.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Float.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Float.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Float().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JButton fiftyCentIncrementBTN;
    private javax.swing.JLabel fiftyCentLabel;
    private javax.swing.JTextField fiftyCentTF;
    private javax.swing.JButton okBTN;
    private javax.swing.JButton onEuroeIncrementBTN;
    private javax.swing.JLabel oneEuroLabel;
    private javax.swing.JTextField oneEuroTF;
    private javax.swing.JButton twentyCentIncrementBTN;
    private javax.swing.JLabel twentyCentLabel;
    private javax.swing.JTextField twentyCentTF;
    private javax.swing.JButton twoEuroIncrementBTN;
    private javax.swing.JLabel twoEuroLabel;
    private javax.swing.JTextField twoEuroTF;
    // End of variables declaration//GEN-END:variables
}
