/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vendingMachine;

import javax.swing.JTextField;
import static vendingMachine.MainGUI.*;
import static vendingMachine.Methods.*;

/**
 *
 * @author cagla
 */
public class Stock extends javax.swing.JFrame {

    public static int cokeOrder = 0;
    public static int fantaOrder = 0;
    public static int mineralOrder = 0;
    public static int waterOrder = 0;
    public static int beerOrder = 0;
    public static int milkOrder = 0;
    
    public void SetToZero() {
        colaTF.setText("0");
        fantaTF.setText("0");
        mineralTF.setText("0");
        waterTF.setText("0");
        beerTF.setText("0");
        milkTF.setText("0");
    }

    public void GetProduct() {
        colaTF.getText();
        fantaTF.getText();
        mineralTF.getText();
        waterTF.getText();
        beerTF.getText();
        milkTF.getText();
    }
    
    public void SetText(JTextField name, int value) {
        name.setText(value + "");
    }

    /**
     * Creates new form stock
     */
    public Stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colaLabel = new javax.swing.JLabel();
        fantaLabel = new javax.swing.JLabel();
        mWaterlabel = new javax.swing.JLabel();
        waterLabel = new javax.swing.JLabel();
        BeerLabel = new javax.swing.JLabel();
        milkLabel = new javax.swing.JLabel();
        colaTF = new javax.swing.JTextField();
        fantaTF = new javax.swing.JTextField();
        mineralTF = new javax.swing.JTextField();
        waterTF = new javax.swing.JTextField();
        beerTF = new javax.swing.JTextField();
        milkTF = new javax.swing.JTextField();
        colaStockIncrementBTN = new javax.swing.JButton();
        mineralStockIncrementBTN = new javax.swing.JButton();
        fantaStockIncrementBTN = new javax.swing.JButton();
        milkStockIncrementBTN = new javax.swing.JButton();
        waterStockIncrementBTN = new javax.swing.JButton();
        beerStockIncrementBTN = new javax.swing.JButton();
        okBTN = new javax.swing.JButton();
        cancelBTN = new javax.swing.JButton();
        clearBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Products");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        colaLabel.setText("Cola");

        fantaLabel.setText("Fanta");

        mWaterlabel.setText("Mineral W.");

        waterLabel.setText("Water");

        BeerLabel.setText("Beer");

        milkLabel.setText("Milk");

        colaTF.setEditable(false);
        colaTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        fantaTF.setEditable(false);
        fantaTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mineralTF.setEditable(false);
        mineralTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        waterTF.setEditable(false);
        waterTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        waterTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterTFActionPerformed(evt);
            }
        });

        beerTF.setEditable(false);
        beerTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        milkTF.setEditable(false);
        milkTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        colaStockIncrementBTN.setText("+");
        colaStockIncrementBTN.setToolTipText("Add product");
        colaStockIncrementBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colaStockIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaStockIncrementBTNActionPerformed(evt);
            }
        });

        mineralStockIncrementBTN.setText("+");
        mineralStockIncrementBTN.setToolTipText("Add product");
        mineralStockIncrementBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mineralStockIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mineralStockIncrementBTNActionPerformed(evt);
            }
        });

        fantaStockIncrementBTN.setText("+");
        fantaStockIncrementBTN.setToolTipText("Add product");
        fantaStockIncrementBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fantaStockIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaStockIncrementBTNActionPerformed(evt);
            }
        });

        milkStockIncrementBTN.setText("+");
        milkStockIncrementBTN.setToolTipText("Add product");
        milkStockIncrementBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        milkStockIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                milkStockIncrementBTNActionPerformed(evt);
            }
        });

        waterStockIncrementBTN.setText("+");
        waterStockIncrementBTN.setToolTipText("Add product");
        waterStockIncrementBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        waterStockIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterStockIncrementBTNActionPerformed(evt);
            }
        });

        beerStockIncrementBTN.setText("+");
        beerStockIncrementBTN.setToolTipText("Add product");
        beerStockIncrementBTN.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        beerStockIncrementBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beerStockIncrementBTNActionPerformed(evt);
            }
        });

        okBTN.setMnemonic('o');
        okBTN.setText("OK");
        okBTN.setToolTipText("OK");
        okBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBTNActionPerformed(evt);
            }
        });

        cancelBTN.setMnemonic('a');
        cancelBTN.setText("Cancel");
        cancelBTN.setToolTipText("Cancel");
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });

        clearBTN.setMnemonic('c');
        clearBTN.setText("Clear");
        clearBTN.setToolTipText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearBTN))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fantaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(milkLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mWaterlabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(waterLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BeerLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(okBTN)
                            .addComponent(colaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelBTN, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fantaTF)
                                    .addComponent(colaTF)
                                    .addComponent(mineralTF)
                                    .addComponent(waterTF)
                                    .addComponent(beerTF)
                                    .addComponent(milkTF, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(colaStockIncrementBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(milkStockIncrementBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fantaStockIncrementBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(mineralStockIncrementBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(beerStockIncrementBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(waterStockIncrementBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(colaStockIncrementBTN)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fantaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fantaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fantaStockIncrementBTN))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mineralTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mineralStockIncrementBTN)
                    .addComponent(mWaterlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(waterTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterStockIncrementBTN)
                    .addComponent(waterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beerStockIncrementBTN)
                    .addComponent(BeerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(milkTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(milkStockIncrementBTN))
                    .addComponent(milkLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBTN)
                    .addComponent(okBTN))
                .addGap(24, 24, 24)
                .addComponent(clearBTN)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        dispose();
        CleanOrder();
        SetToZero();
    }//GEN-LAST:event_cancelBTNActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        SetToZero();
        CleanOrder();
    }//GEN-LAST:event_formWindowOpened

    private void colaStockIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaStockIncrementBTNActionPerformed
        cokeOrder++;
        SetText(colaTF,cokeOrder);
    }//GEN-LAST:event_colaStockIncrementBTNActionPerformed

    private void fantaStockIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaStockIncrementBTNActionPerformed
        fantaOrder++;
        SetText(fantaTF,fantaOrder);
    }//GEN-LAST:event_fantaStockIncrementBTNActionPerformed

    private void mineralStockIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mineralStockIncrementBTNActionPerformed
        mineralOrder++;
        SetText(mineralTF,mineralOrder);
    }//GEN-LAST:event_mineralStockIncrementBTNActionPerformed

    private void waterStockIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterStockIncrementBTNActionPerformed
        waterOrder++;
        SetText(waterTF,waterOrder);
    }//GEN-LAST:event_waterStockIncrementBTNActionPerformed

    private void beerStockIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beerStockIncrementBTNActionPerformed
        beerOrder++;
        SetText(beerTF,beerOrder);
    }//GEN-LAST:event_beerStockIncrementBTNActionPerformed

    private void milkStockIncrementBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_milkStockIncrementBTNActionPerformed
        milkOrder++;
        SetText(milkTF,milkOrder);
    }//GEN-LAST:event_milkStockIncrementBTNActionPerformed

    private void okBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBTNActionPerformed
        //Do i need try and catch? Because all orders set to 0 at beginning.
        GetProduct();
        dispose();
    }//GEN-LAST:event_okBTNActionPerformed

    private void waterTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waterTFActionPerformed

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        CleanOrder();
        SetToZero();
    }//GEN-LAST:event_clearBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BeerLabel;
    private javax.swing.JButton beerStockIncrementBTN;
    private javax.swing.JTextField beerTF;
    private javax.swing.JButton cancelBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JLabel colaLabel;
    private javax.swing.JButton colaStockIncrementBTN;
    private javax.swing.JTextField colaTF;
    private javax.swing.JLabel fantaLabel;
    private javax.swing.JButton fantaStockIncrementBTN;
    private javax.swing.JTextField fantaTF;
    private javax.swing.JLabel mWaterlabel;
    private javax.swing.JLabel milkLabel;
    private javax.swing.JButton milkStockIncrementBTN;
    private javax.swing.JTextField milkTF;
    private javax.swing.JButton mineralStockIncrementBTN;
    private javax.swing.JTextField mineralTF;
    private javax.swing.JButton okBTN;
    private javax.swing.JLabel waterLabel;
    private javax.swing.JButton waterStockIncrementBTN;
    private javax.swing.JTextField waterTF;
    // End of variables declaration//GEN-END:variables

}
